// <auto-generated />
using System;
using EfCoreMigrations.DB;
using EfCoreMigrations.DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EfCoreMigrations.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20241003134753_EditedVipPassenger")]
    partial class EditedVipPassenger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("companies");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.PassengerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("passenges");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.PassengerTripAuxilatyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.ToTable("passengertrips");
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.TripEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Plane")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plane");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_in");

                    b.Property<DateTime>("TimeOut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_out");

                    b.Property<string>("TownFrom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("town_from");

                    b.Property<string>("TownTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("town_to");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("trips");

                    b.HasDiscriminator().HasValue("TripEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.StateOwnedCompanyEntity", b =>
                {
                    b.HasBaseType("EfCoreMigrations.DB.Entities.CompanyEntity");

                    b.Property<string>("CompanyCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("state_owned_companies");
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.VipPassengerEntity", b =>
                {
                    b.HasBaseType("EfCoreMigrations.DB.Entities.PassengerEntity");

                    b.Property<VipStatus>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.ToTable("vip_passengers");
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.PlaneTripEntity", b =>
                {
                    b.HasBaseType("EfCoreMigrations.DB.Entities.TripEntity");

                    b.Property<int>("PlaneId")
                        .HasColumnType("integer");

                    b.ToTable("trips");

                    b.HasDiscriminator().HasValue("PlaneTripEntity");
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.PassengerTripAuxilatyEntity", b =>
                {
                    b.HasOne("EfCoreMigrations.DB.Entities.PassengerEntity", "Passenger")
                        .WithMany("PassengerTrips")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreMigrations.DB.Entities.TripEntity", "Trip")
                        .WithMany("PassengerTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.TripEntity", b =>
                {
                    b.HasOne("EfCoreMigrations.DB.Entities.CompanyEntity", "Company")
                        .WithMany("tripModels")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.StateOwnedCompanyEntity", b =>
                {
                    b.HasOne("EfCoreMigrations.DB.Entities.CompanyEntity", null)
                        .WithOne()
                        .HasForeignKey("EfCoreMigrations.DB.Entities.StateOwnedCompanyEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.CompanyEntity", b =>
                {
                    b.Navigation("tripModels");
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.PassengerEntity", b =>
                {
                    b.Navigation("PassengerTrips");
                });

            modelBuilder.Entity("EfCoreMigrations.DB.Entities.TripEntity", b =>
                {
                    b.Navigation("PassengerTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
